version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7-stretch
      - image: circleci/dynamodb
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install awscli
      - run:
          name: Configure aws
          command: |
            aws configure set aws_access_key_id test
            aws configure set aws_secret_access_key test
            aws configure set region eu-central-1
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for dynamodb
          command: dockerize -wait tcp://localhost:8000 -timeout 1m
      - run:
          name: Run tests
          command: pytest
  deploy_dev:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install setuptools wheel twine
      - run:
          name: Init .pypirc
          command: |
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME_TEST" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD_TEST" >> ~/.pypirc
      - run:
          command: |
            python3 setup.py sdist bdist_wheel
          name: Create packages
      - run:
          name: upload to testpypi
          command: |
            twine upload --repository testpypi dist/*
  deploy_prod:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install setuptools wheel twine
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME_PROD" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD_PROD" >> ~/.pypirc
      - run:
          command: |
            python3 setup.py sdist bdist_wheel
          name: Create packages
      - run:
          name: upload to pypi
          command: |
            twine upload --repository pypi dist/*

workflows:
  main:
    jobs:
      - test:
        filters:
          branches:
            only:
              - dev
              - master
      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - test
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - test
